version: "3"

# network
#networks:
#  demo-bridge:
#    driver: bridge
    
# services
services:
  # mysql
  my-mysql:
    container_name: localhost
    build:
      dockerfile: dockerfile_mysql
      context: D:/shell_and_docker_19032121/demo_docker_compose/
    hostname: my_sql
    restart: always
#    networks:
 #     - demo-bridge
#    volumes:
#      - /D/docker_composev1/db:/home/db
  # my-java
  my-java:
    container_name: my_java
    build:
      dockerfile: dockerfile_environment_java
      context: D:/shell_and_docker_19032121/demo_docker_compose/
    hostname: my-java
    restart: always
#    networks:
#      - demo-bridge
    ports:
      - "8080:8080"
    links:
      - my-mysql  
           